version: '3.7'

volumes:
  mysql_data: {}
  rainloop_data: {}

services:

  wordpress:
    image: wordpress:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    ports:
      - ${WP_PORTS:-80}
    volumes:
      - ${WORDPRESS_LOCATION:-./html}:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define('WP_ALLOW_MULTISITE', ${WP_ALLOW_MULTISITE:-false} );

###############################################################
  nginx:
    image: nginx:1.14
    ports:
      - "80:80"
      - "443:443"
      - "10080"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled/
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./ssl:/etc/ssl/local/

###############################################################
  mysql:
    image: mysql:8.0.12
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${MYSQL_PORTS:-3306}

###############################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=${PHP_MY_ADMIN_URI}
    restart: always
    ports:
      - ${PHPMYADMIN_PORTS:-8000}
    volumes:
      - /sessions

###############################################################
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    ports:
      - ${RAINLOOP_PORTS:-8888}
    volumes:
      - rainloop_data:/rainloop/data

###############################################################

  mailhog:
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_SERVER_PORTS:-1025}
      - ${MAILHOG_CLIENT_PORTS:-8025:8025}